language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install flake8
  - pip install -r requirements.txt
  - pip freeze
before_script:
  - cd wangwang
script:
  - flake8 .
  - tox -e py36
  - isort *.py -c -vb
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test